---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: green-team
  namespace: simple-webapp-green
spec:
  interval: 1m0s
  path: ./
  prune: false
  serviceAccountName: green-team
  sourceRef:
    kind: GitRepository
    name: green-team
