---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: green-team
  namespace: simple-webapp-green
spec:
  interval: 1m0s
  ref:
    branch: main
  url: https://github.com/la-cc/simple-webapp-green.git
