---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: blue-team
  name: simple-webapp-blue
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: blue-team
  name: blue-team
  namespace: simple-webapp-blue
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: blue-team
  name: blue-team-reconciler
  namespace: simple-webapp-blue
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: gotk:simple-webapp-blue:reconciler
- kind: ServiceAccount
  name: blue-team
  namespace: simple-webapp-blue
