apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: blue-team
  namespace: simple-webapp-blue
spec:
  interval: 1m0s
  path: ./tenants/blue-team
  prune: false
  serviceAccountName: blue-team
  sourceRef:
    kind: GitRepository
    name: blue-team
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: green-team
  namespace: simple-webapp-green
spec:
  interval: 1m0s
  path: ./tenants/green-team
  prune: false
  serviceAccountName: green-team
  sourceRef:
    kind: GitRepository
    name: green-team
