apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  chart:
    spec:
      version: ">=1.0.0-alpha"
  test:
    enable: false
  values:
    ingress:
      annotations: 
       kubernetes.io/ingress.class: nginx
       cert-manager.io/cluster-issuer: letsencrypt-nginx
      hosts:
        - host: podinfo.qavps.com
          paths:
            - path: /
              pathType: ImplementationSpecific
      tls: 
       - secretName: chart-example-tls
         hosts:
          - podinfo.qavps.com